/*
 * Pet Shop API
 * Pet Shop API A comprehensive example of Micronaut application best practices for a pet shop
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package io.seqera.api.exchange;

import java.util.Objects;
import java.util.Arrays;
import java.util.Map;
import java.util.function.Function;
import java.util.stream.Collectors;
import com.fasterxml.jackson.annotation.*;
import io.micronaut.serde.annotation.Serdeable;
import jakarta.validation.constraints.*;
import jakarta.validation.Valid;
import io.micronaut.core.annotation.Nullable;
import jakarta.annotation.Generated;

/**
 * Pet creation request
 */
@Serdeable
@JsonPropertyOrder({
    CreatePetRequest.JSON_PROPERTY_NAME,
    CreatePetRequest.JSON_PROPERTY_SPECIES,
    CreatePetRequest.JSON_PROPERTY_AGE,
    CreatePetRequest.JSON_PROPERTY_BREED,
    CreatePetRequest.JSON_PROPERTY_COLOR,
    CreatePetRequest.JSON_PROPERTY_DESCRIPTION,
})
@Generated("io.micronaut.openapi.generator.JavaMicronautServerCodegen")
public class CreatePetRequest {

    public static final String JSON_PROPERTY_NAME = "name";
    public static final String JSON_PROPERTY_SPECIES = "species";
    public static final String JSON_PROPERTY_AGE = "age";
    public static final String JSON_PROPERTY_BREED = "breed";
    public static final String JSON_PROPERTY_COLOR = "color";
    public static final String JSON_PROPERTY_DESCRIPTION = "description";

    /**
     * Pet&#39;s name
     */
    @NotNull
    @Size(min = 1, max = 100)
    @JsonProperty(JSON_PROPERTY_NAME)
    private String name;

    /**
     * Pet species (e.g., dog, cat, bird)
     */
    @NotNull
    @Size(min = 1, max = 50)
    @JsonProperty(JSON_PROPERTY_SPECIES)
    private String species;

    /**
     * Pet age in years
     */
    @NotNull
    @Min(0)
    @Max(50)
    @JsonProperty(JSON_PROPERTY_AGE)
    private Integer age;

    /**
     * Pet breed
     */
    @Nullable(inherited = true)
    @Size(max = 50)
    @JsonProperty(JSON_PROPERTY_BREED)
    @JsonInclude(JsonInclude.Include.USE_DEFAULTS)
    private String breed;

    /**
     * Pet color
     */
    @Nullable(inherited = true)
    @Size(max = 20)
    @JsonProperty(JSON_PROPERTY_COLOR)
    @JsonInclude(JsonInclude.Include.USE_DEFAULTS)
    private String color;

    /**
     * Pet description
     */
    @Nullable(inherited = true)
    @Size(max = 500)
    @JsonProperty(JSON_PROPERTY_DESCRIPTION)
    @JsonInclude(JsonInclude.Include.USE_DEFAULTS)
    private String description;

    public CreatePetRequest(String name, String species, Integer age) {
        this.name = name;
        this.species = species;
        this.age = age;
    }

    /**
     * Pet&#39;s name
     *
     * @return the name property value
     */
    public String getName() {
        return name;
    }

    /**
     * Set the name property value
     *
     * @param name property value to set
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * Set name in a chainable fashion.
     *
     * @return The same instance of CreatePetRequest for chaining.
     */
    public CreatePetRequest name(String name) {
        this.name = name;
        return this;
    }

    /**
     * Pet species (e.g., dog, cat, bird)
     *
     * @return the species property value
     */
    public String getSpecies() {
        return species;
    }

    /**
     * Set the species property value
     *
     * @param species property value to set
     */
    public void setSpecies(String species) {
        this.species = species;
    }

    /**
     * Set species in a chainable fashion.
     *
     * @return The same instance of CreatePetRequest for chaining.
     */
    public CreatePetRequest species(String species) {
        this.species = species;
        return this;
    }

    /**
     * Pet age in years
     *
     * @return the age property value
     */
    public Integer getAge() {
        return age;
    }

    /**
     * Set the age property value
     *
     * @param age property value to set
     */
    public void setAge(Integer age) {
        this.age = age;
    }

    /**
     * Set age in a chainable fashion.
     *
     * @return The same instance of CreatePetRequest for chaining.
     */
    public CreatePetRequest age(Integer age) {
        this.age = age;
        return this;
    }

    /**
     * Pet breed
     *
     * @return the breed property value
     */
    public String getBreed() {
        return breed;
    }

    /**
     * Set the breed property value
     *
     * @param breed property value to set
     */
    public void setBreed(String breed) {
        this.breed = breed;
    }

    /**
     * Set breed in a chainable fashion.
     *
     * @return The same instance of CreatePetRequest for chaining.
     */
    public CreatePetRequest breed(String breed) {
        this.breed = breed;
        return this;
    }

    /**
     * Pet color
     *
     * @return the color property value
     */
    public String getColor() {
        return color;
    }

    /**
     * Set the color property value
     *
     * @param color property value to set
     */
    public void setColor(String color) {
        this.color = color;
    }

    /**
     * Set color in a chainable fashion.
     *
     * @return The same instance of CreatePetRequest for chaining.
     */
    public CreatePetRequest color(String color) {
        this.color = color;
        return this;
    }

    /**
     * Pet description
     *
     * @return the description property value
     */
    public String getDescription() {
        return description;
    }

    /**
     * Set the description property value
     *
     * @param description property value to set
     */
    public void setDescription(String description) {
        this.description = description;
    }

    /**
     * Set description in a chainable fashion.
     *
     * @return The same instance of CreatePetRequest for chaining.
     */
    public CreatePetRequest description(String description) {
        this.description = description;
        return this;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        var createPetRequest = (CreatePetRequest) o;
        return Objects.equals(name, createPetRequest.name)
            && Objects.equals(species, createPetRequest.species)
            && Objects.equals(age, createPetRequest.age)
            && Objects.equals(breed, createPetRequest.breed)
            && Objects.equals(color, createPetRequest.color)
            && Objects.equals(description, createPetRequest.description);
    }

    @Override
    public int hashCode() {
        return Objects.hash(name, species, age, breed, color, description);
    }

    @Override
    public String toString() {
        return "CreatePetRequest("
            + "name: " + getName() + ", "
            + "species: " + getSpecies() + ", "
            + "age: " + getAge() + ", "
            + "breed: " + getBreed() + ", "
            + "color: " + getColor() + ", "
            + "description: " + getDescription()
            + ")";
    }

}