/*
 * Pet Shop API
 * Pet Shop API A comprehensive example of Micronaut application best practices for a pet shop
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package io.seqera.api.exchange;

import java.util.Objects;
import java.util.Arrays;
import java.util.Map;
import java.util.function.Function;
import java.util.stream.Collectors;
import io.seqera.api.exchange.Pet;
import com.fasterxml.jackson.annotation.*;
import io.micronaut.serde.annotation.Serdeable;
import jakarta.validation.constraints.*;
import jakarta.validation.Valid;
import io.micronaut.core.annotation.Nullable;
import jakarta.annotation.Generated;

/**
 * Get pet response
 */
@Serdeable
@JsonPropertyOrder(GetPetResponse.JSON_PROPERTY_PET)
@Generated("io.micronaut.openapi.generator.JavaMicronautServerCodegen")
public class GetPetResponse {

    public static final String JSON_PROPERTY_PET = "pet";

    @NotNull
    @Valid
    @JsonProperty(JSON_PROPERTY_PET)
    private Pet pet;

    public GetPetResponse(Pet pet) {
        this.pet = pet;
    }

    /**
     * @return the pet property value
     */
    public Pet getPet() {
        return pet;
    }

    /**
     * Set the pet property value
     *
     * @param pet property value to set
     */
    public void setPet(Pet pet) {
        this.pet = pet;
    }

    /**
     * Set pet in a chainable fashion.
     *
     * @return The same instance of GetPetResponse for chaining.
     */
    public GetPetResponse pet(Pet pet) {
        this.pet = pet;
        return this;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        var getPetResponse = (GetPetResponse) o;
        return Objects.equals(pet, getPetResponse.pet);
    }

    @Override
    public int hashCode() {
        return Objects.hash(pet);
    }

    @Override
    public String toString() {
        return "GetPetResponse("
            + "pet: " + getPet()
            + ")";
    }

}