/*
 * Pet Shop API
 * Pet Shop API A comprehensive example of Micronaut application best practices for a pet shop
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package io.seqera.api.exchange;

import java.util.Objects;
import java.util.Arrays;
import java.util.Map;
import java.util.function.Function;
import java.util.stream.Collectors;
import io.seqera.api.exchange.Pet;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import com.fasterxml.jackson.annotation.*;
import io.micronaut.serde.annotation.Serdeable;
import jakarta.validation.constraints.*;
import jakarta.validation.Valid;
import io.micronaut.core.annotation.Nullable;
import jakarta.annotation.Generated;

/**
 * List pets response
 */
@Serdeable
@JsonPropertyOrder(ListPetsResponse.JSON_PROPERTY_PETS)
@Generated("io.micronaut.openapi.generator.JavaMicronautServerCodegen")
public class ListPetsResponse {

    public static final String JSON_PROPERTY_PETS = "pets";

    @NotNull
    @JsonProperty(JSON_PROPERTY_PETS)
    private List<@Valid Pet> pets;

    public ListPetsResponse(List<@Valid Pet> pets) {
        this.pets = pets;
    }

    /**
     * @return the pets property value
     */
    public List<@Valid Pet> getPets() {
        return pets;
    }

    /**
     * Set the pets property value
     *
     * @param pets property value to set
     */
    public void setPets(List<@Valid Pet> pets) {
        this.pets = pets;
    }

    /**
     * Set pets in a chainable fashion.
     *
     * @return The same instance of ListPetsResponse for chaining.
     */
    public ListPetsResponse pets(List<@Valid Pet> pets) {
        this.pets = pets;
        return this;
    }
    /**
     * Add an item to the pets property in a chainable fashion.
     *
     * @return The same instance of ListPetsResponse for chaining.
     */
    public ListPetsResponse addPetsItem(Pet petsItem) {
        pets.add(petsItem);
        return this;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        var listPetsResponse = (ListPetsResponse) o;
        return Objects.equals(pets, listPetsResponse.pets);
    }

    @Override
    public int hashCode() {
        return Objects.hash(pets);
    }

    @Override
    public String toString() {
        return "ListPetsResponse("
            + "pets: " + getPets()
            + ")";
    }

}