/*
 * Pet Shop API
 * Pet Shop API A comprehensive example of Micronaut application best practices for a pet shop
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package io.seqera.api.spec;

import io.micronaut.http.annotation.*;
import io.micronaut.core.annotation.Nullable;
import io.micronaut.core.convert.format.Format;
import io.seqera.api.model.CreatePetRequest;
import io.seqera.api.model.CreatePetResponse;
import io.seqera.api.model.ErrorResponse;
import io.seqera.api.model.GetPetResponse;
import io.micronaut.http.HttpResponse;
import io.seqera.api.model.ListPetsResponse;
import io.seqera.api.model.UpdatePetRequest;
import io.seqera.api.model.UpdatePetResponse;
import jakarta.annotation.Generated;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import jakarta.validation.Valid;
import jakarta.validation.constraints.*;

@Generated("io.micronaut.openapi.generator.JavaMicronautServerCodegen")
@Controller
public interface PetsApiSpec {

    /**
     * Create a new pet
     *
     * @param createPetRequest (required)
     * @return The request has succeeded. (status code 200)
     *         or An unexpected error response. (status code default)
     */
    @Post("/api/v1/pets/")
    CreatePetResponse createPet(
        @Body @NotNull @Valid CreatePetRequest createPetRequest
    );

    /**
     * Delete a pet
     *
     * @param id (required)
     * @return There is no content to send for this request, but the headers may be useful.  (status code 204)
     *         or An unexpected error response. (status code default)
     */
    @Delete("/api/v1/pets/{id}")
    HttpResponse<Void> deletePet(
        @PathVariable("id") @NotNull Long id
    );

    /**
     * Get pet by ID
     *
     * @param id (required)
     * @return The request has succeeded. (status code 200)
     *         or An unexpected error response. (status code default)
     */
    @Get("/api/v1/pets/{id}")
    GetPetResponse getPet(
        @PathVariable("id") @NotNull Long id
    );

    /**
     * List all pets
     *
     * @return The request has succeeded. (status code 200)
     */
    @Get("/api/v1/pets/")
    ListPetsResponse listPets();

    /**
     * Update an existing pet
     *
     * @param id (required)
     * @param updatePetRequest (required)
     * @return The request has succeeded. (status code 200)
     *         or An unexpected error response. (status code default)
     */
    @Put("/api/v1/pets/{id}")
    UpdatePetResponse updatePet(
        @PathVariable("id") @NotNull Long id,
        @Body @NotNull @Valid UpdatePetRequest updatePetRequest
    );

}