/* tslint:disable */
/* eslint-disable */
/**
 * Pet Shop API
 * Pet Shop API A comprehensive example of Micronaut application best practices for a pet shop
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Pet creation request
 * @export
 * @interface CreatePetRequest
 */
export interface CreatePetRequest {
    /**
     * Pet's name
     * @type {string}
     * @memberof CreatePetRequest
     */
    name: string;
    /**
     * Pet species (e.g., dog, cat, bird)
     * @type {string}
     * @memberof CreatePetRequest
     */
    species: string;
    /**
     * Pet breed
     * @type {string}
     * @memberof CreatePetRequest
     */
    breed?: string;
    /**
     * Pet age in years
     * @type {number}
     * @memberof CreatePetRequest
     */
    age: number;
    /**
     * Pet color
     * @type {string}
     * @memberof CreatePetRequest
     */
    color?: string;
    /**
     * Pet description
     * @type {string}
     * @memberof CreatePetRequest
     */
    description?: string;
}

/**
 * Check if a given object implements the CreatePetRequest interface.
 */
export function instanceOfCreatePetRequest(value: object): value is CreatePetRequest {
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('species' in value) || value['species'] === undefined) return false;
    if (!('age' in value) || value['age'] === undefined) return false;
    return true;
}

export function CreatePetRequestFromJSON(json: any): CreatePetRequest {
    return CreatePetRequestFromJSONTyped(json, false);
}

export function CreatePetRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreatePetRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'],
        'species': json['species'],
        'breed': json['breed'] == null ? undefined : json['breed'],
        'age': json['age'],
        'color': json['color'] == null ? undefined : json['color'],
        'description': json['description'] == null ? undefined : json['description'],
    };
}

export function CreatePetRequestToJSON(value?: CreatePetRequest | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'name': value['name'],
        'species': value['species'],
        'breed': value['breed'],
        'age': value['age'],
        'color': value['color'],
        'description': value['description'],
    };
}

