/* tslint:disable */
/* eslint-disable */
/**
 * Pet Shop API
 * Pet Shop API A comprehensive example of Micronaut application best practices for a pet shop
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Pet } from './Pet';
import {
    PetFromJSON,
    PetFromJSONTyped,
    PetToJSON,
} from './Pet';

/**
 * Pet creation response
 * @export
 * @interface CreatePetResponse
 */
export interface CreatePetResponse {
    /**
     * 
     * @type {Pet}
     * @memberof CreatePetResponse
     */
    pet: Pet;
}

/**
 * Check if a given object implements the CreatePetResponse interface.
 */
export function instanceOfCreatePetResponse(value: object): value is CreatePetResponse {
    if (!('pet' in value) || value['pet'] === undefined) return false;
    return true;
}

export function CreatePetResponseFromJSON(json: any): CreatePetResponse {
    return CreatePetResponseFromJSONTyped(json, false);
}

export function CreatePetResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreatePetResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'pet': PetFromJSON(json['pet']),
    };
}

export function CreatePetResponseToJSON(value?: CreatePetResponse | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'pet': PetToJSON(value['pet']),
    };
}

