/* tslint:disable */
/* eslint-disable */
/**
 * Pet Shop API
 * Pet Shop API A comprehensive example of Micronaut application best practices for a pet shop
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Pet } from './Pet';
import {
    PetFromJSON,
    PetFromJSONTyped,
    PetToJSON,
} from './Pet';

/**
 * Get pet response
 * @export
 * @interface GetPetResponse
 */
export interface GetPetResponse {
    /**
     * 
     * @type {Pet}
     * @memberof GetPetResponse
     */
    pet: Pet;
}

/**
 * Check if a given object implements the GetPetResponse interface.
 */
export function instanceOfGetPetResponse(value: object): value is GetPetResponse {
    if (!('pet' in value) || value['pet'] === undefined) return false;
    return true;
}

export function GetPetResponseFromJSON(json: any): GetPetResponse {
    return GetPetResponseFromJSONTyped(json, false);
}

export function GetPetResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetPetResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'pet': PetFromJSON(json['pet']),
    };
}

export function GetPetResponseToJSON(value?: GetPetResponse | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'pet': PetToJSON(value['pet']),
    };
}

