/* tslint:disable */
/* eslint-disable */
/**
 * Pet Shop API
 * Pet Shop API A comprehensive example of Micronaut application best practices for a pet shop
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Pet model for API responses
 * @export
 * @interface Pet
 */
export interface Pet {
    /**
     * Pet ID
     * @type {number}
     * @memberof Pet
     */
    id: number;
    /**
     * Pet's name
     * @type {string}
     * @memberof Pet
     */
    name: string;
    /**
     * Pet species (e.g., dog, cat, bird)
     * @type {string}
     * @memberof Pet
     */
    species: string;
    /**
     * Pet breed
     * @type {string}
     * @memberof Pet
     */
    breed?: string;
    /**
     * Pet age in years
     * @type {number}
     * @memberof Pet
     */
    age: number;
    /**
     * Pet color
     * @type {string}
     * @memberof Pet
     */
    color?: string;
    /**
     * Pet description
     * @type {string}
     * @memberof Pet
     */
    description?: string;
    /**
     * Whether the pet is available for adoption
     * @type {boolean}
     * @memberof Pet
     */
    isAvailable: boolean;
    /**
     * Creation timestamp
     * @type {Date}
     * @memberof Pet
     */
    createdAt: Date;
    /**
     * Last update timestamp
     * @type {Date}
     * @memberof Pet
     */
    updatedAt: Date;
}

/**
 * Check if a given object implements the Pet interface.
 */
export function instanceOfPet(value: object): value is Pet {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('species' in value) || value['species'] === undefined) return false;
    if (!('age' in value) || value['age'] === undefined) return false;
    if (!('isAvailable' in value) || value['isAvailable'] === undefined) return false;
    if (!('createdAt' in value) || value['createdAt'] === undefined) return false;
    if (!('updatedAt' in value) || value['updatedAt'] === undefined) return false;
    return true;
}

export function PetFromJSON(json: any): Pet {
    return PetFromJSONTyped(json, false);
}

export function PetFromJSONTyped(json: any, ignoreDiscriminator: boolean): Pet {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'name': json['name'],
        'species': json['species'],
        'breed': json['breed'] == null ? undefined : json['breed'],
        'age': json['age'],
        'color': json['color'] == null ? undefined : json['color'],
        'description': json['description'] == null ? undefined : json['description'],
        'isAvailable': json['isAvailable'],
        'createdAt': (new Date(json['createdAt'])),
        'updatedAt': (new Date(json['updatedAt'])),
    };
}

export function PetToJSON(value?: Pet | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'id': value['id'],
        'name': value['name'],
        'species': value['species'],
        'breed': value['breed'],
        'age': value['age'],
        'color': value['color'],
        'description': value['description'],
        'isAvailable': value['isAvailable'],
        'createdAt': ((value['createdAt']).toISOString()),
        'updatedAt': ((value['updatedAt']).toISOString()),
    };
}

