/* tslint:disable */
/* eslint-disable */
/**
 * Pet Shop API
 * Pet Shop API A comprehensive example of Micronaut application best practices for a pet shop
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Service information model
 * @export
 * @interface ServiceInfo
 */
export interface ServiceInfo {
    /**
     * Application version
     * @type {string}
     * @memberof ServiceInfo
     */
    version: string;
    /**
     * Build commit ID
     * @type {string}
     * @memberof ServiceInfo
     */
    commitId: string;
}

/**
 * Check if a given object implements the ServiceInfo interface.
 */
export function instanceOfServiceInfo(value: object): value is ServiceInfo {
    if (!('version' in value) || value['version'] === undefined) return false;
    if (!('commitId' in value) || value['commitId'] === undefined) return false;
    return true;
}

export function ServiceInfoFromJSON(json: any): ServiceInfo {
    return ServiceInfoFromJSONTyped(json, false);
}

export function ServiceInfoFromJSONTyped(json: any, ignoreDiscriminator: boolean): ServiceInfo {
    if (json == null) {
        return json;
    }
    return {
        
        'version': json['version'],
        'commitId': json['commitId'],
    };
}

export function ServiceInfoToJSON(value?: ServiceInfo | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'version': value['version'],
        'commitId': value['commitId'],
    };
}

