/* tslint:disable */
/* eslint-disable */
/**
 * Pet Shop API
 * Pet Shop API A comprehensive example of Micronaut application best practices for a pet shop
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ServiceInfo } from './ServiceInfo';
import {
    ServiceInfoFromJSON,
    ServiceInfoFromJSONTyped,
    ServiceInfoToJSON,
} from './ServiceInfo';

/**
 * Service information response
 * @export
 * @interface ServiceInfoResponse
 */
export interface ServiceInfoResponse {
    /**
     * 
     * @type {ServiceInfo}
     * @memberof ServiceInfoResponse
     */
    serviceInfo: ServiceInfo;
}

/**
 * Check if a given object implements the ServiceInfoResponse interface.
 */
export function instanceOfServiceInfoResponse(value: object): value is ServiceInfoResponse {
    if (!('serviceInfo' in value) || value['serviceInfo'] === undefined) return false;
    return true;
}

export function ServiceInfoResponseFromJSON(json: any): ServiceInfoResponse {
    return ServiceInfoResponseFromJSONTyped(json, false);
}

export function ServiceInfoResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ServiceInfoResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'serviceInfo': ServiceInfoFromJSON(json['serviceInfo']),
    };
}

export function ServiceInfoResponseToJSON(value?: ServiceInfoResponse | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'serviceInfo': ServiceInfoToJSON(value['serviceInfo']),
    };
}

