/*
 * Pet Shop API
 * Pet Shop API A comprehensive example of Micronaut application best practices for a pet shop
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package io.seqera.api.model;

import java.util.Objects;
import java.util.Arrays;
import java.util.Map;
import java.util.function.Function;
import java.util.stream.Collectors;
import java.time.OffsetDateTime;
import com.fasterxml.jackson.annotation.*;
import io.micronaut.serde.annotation.Serdeable;
import jakarta.validation.constraints.*;
import jakarta.validation.Valid;
import io.micronaut.core.annotation.Nullable;
import jakarta.annotation.Generated;

/**
 * Pet model for API responses
 */
@Serdeable
@JsonPropertyOrder({
    Pet.JSON_PROPERTY_ID,
    Pet.JSON_PROPERTY_NAME,
    Pet.JSON_PROPERTY_SPECIES,
    Pet.JSON_PROPERTY_AGE,
    Pet.JSON_PROPERTY_IS_AVAILABLE,
    Pet.JSON_PROPERTY_CREATED_AT,
    Pet.JSON_PROPERTY_UPDATED_AT,
    Pet.JSON_PROPERTY_BREED,
    Pet.JSON_PROPERTY_COLOR,
    Pet.JSON_PROPERTY_DESCRIPTION,
})
@Generated("io.micronaut.openapi.generator.JavaMicronautServerCodegen")
public class Pet {

    public static final String JSON_PROPERTY_ID = "id";
    public static final String JSON_PROPERTY_NAME = "name";
    public static final String JSON_PROPERTY_SPECIES = "species";
    public static final String JSON_PROPERTY_AGE = "age";
    public static final String JSON_PROPERTY_IS_AVAILABLE = "isAvailable";
    public static final String JSON_PROPERTY_CREATED_AT = "createdAt";
    public static final String JSON_PROPERTY_UPDATED_AT = "updatedAt";
    public static final String JSON_PROPERTY_BREED = "breed";
    public static final String JSON_PROPERTY_COLOR = "color";
    public static final String JSON_PROPERTY_DESCRIPTION = "description";

    /**
     * Pet ID
     */
    @NotNull
    @JsonProperty(JSON_PROPERTY_ID)
    private Long id;

    /**
     * Pet&#39;s name
     */
    @NotNull
    @JsonProperty(JSON_PROPERTY_NAME)
    private String name;

    /**
     * Pet species (e.g., dog, cat, bird)
     */
    @NotNull
    @JsonProperty(JSON_PROPERTY_SPECIES)
    private String species;

    /**
     * Pet age in years
     */
    @NotNull
    @JsonProperty(JSON_PROPERTY_AGE)
    private Integer age;

    /**
     * Whether the pet is available for adoption
     */
    @NotNull
    @JsonProperty(JSON_PROPERTY_IS_AVAILABLE)
    private Boolean isAvailable;

    /**
     * Creation timestamp
     */
    @NotNull
    @JsonProperty(JSON_PROPERTY_CREATED_AT)
    private OffsetDateTime createdAt;

    /**
     * Last update timestamp
     */
    @NotNull
    @JsonProperty(JSON_PROPERTY_UPDATED_AT)
    private OffsetDateTime updatedAt;

    /**
     * Pet breed
     */
    @Nullable(inherited = true)
    @JsonProperty(JSON_PROPERTY_BREED)
    @JsonInclude(JsonInclude.Include.USE_DEFAULTS)
    private String breed;

    /**
     * Pet color
     */
    @Nullable(inherited = true)
    @JsonProperty(JSON_PROPERTY_COLOR)
    @JsonInclude(JsonInclude.Include.USE_DEFAULTS)
    private String color;

    /**
     * Pet description
     */
    @Nullable(inherited = true)
    @JsonProperty(JSON_PROPERTY_DESCRIPTION)
    @JsonInclude(JsonInclude.Include.USE_DEFAULTS)
    private String description;

    public Pet(Long id, String name, String species, Integer age, Boolean isAvailable, OffsetDateTime createdAt, OffsetDateTime updatedAt) {
        this.id = id;
        this.name = name;
        this.species = species;
        this.age = age;
        this.isAvailable = isAvailable;
        this.createdAt = createdAt;
        this.updatedAt = updatedAt;
    }

    /**
     * Pet ID
     *
     * @return the id property value
     */
    public Long getId() {
        return id;
    }

    /**
     * Set the id property value
     *
     * @param id property value to set
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * Set id in a chainable fashion.
     *
     * @return The same instance of Pet for chaining.
     */
    public Pet id(Long id) {
        this.id = id;
        return this;
    }

    /**
     * Pet&#39;s name
     *
     * @return the name property value
     */
    public String getName() {
        return name;
    }

    /**
     * Set the name property value
     *
     * @param name property value to set
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * Set name in a chainable fashion.
     *
     * @return The same instance of Pet for chaining.
     */
    public Pet name(String name) {
        this.name = name;
        return this;
    }

    /**
     * Pet species (e.g., dog, cat, bird)
     *
     * @return the species property value
     */
    public String getSpecies() {
        return species;
    }

    /**
     * Set the species property value
     *
     * @param species property value to set
     */
    public void setSpecies(String species) {
        this.species = species;
    }

    /**
     * Set species in a chainable fashion.
     *
     * @return The same instance of Pet for chaining.
     */
    public Pet species(String species) {
        this.species = species;
        return this;
    }

    /**
     * Pet age in years
     *
     * @return the age property value
     */
    public Integer getAge() {
        return age;
    }

    /**
     * Set the age property value
     *
     * @param age property value to set
     */
    public void setAge(Integer age) {
        this.age = age;
    }

    /**
     * Set age in a chainable fashion.
     *
     * @return The same instance of Pet for chaining.
     */
    public Pet age(Integer age) {
        this.age = age;
        return this;
    }

    /**
     * Whether the pet is available for adoption
     *
     * @return the isAvailable property value
     */
    public Boolean getIsAvailable() {
        return isAvailable;
    }

    /**
     * Set the isAvailable property value
     *
     * @param isAvailable property value to set
     */
    public void setIsAvailable(Boolean isAvailable) {
        this.isAvailable = isAvailable;
    }

    /**
     * Set isAvailable in a chainable fashion.
     *
     * @return The same instance of Pet for chaining.
     */
    public Pet isAvailable(Boolean isAvailable) {
        this.isAvailable = isAvailable;
        return this;
    }

    /**
     * Creation timestamp
     *
     * @return the createdAt property value
     */
    public OffsetDateTime getCreatedAt() {
        return createdAt;
    }

    /**
     * Set the createdAt property value
     *
     * @param createdAt property value to set
     */
    public void setCreatedAt(OffsetDateTime createdAt) {
        this.createdAt = createdAt;
    }

    /**
     * Set createdAt in a chainable fashion.
     *
     * @return The same instance of Pet for chaining.
     */
    public Pet createdAt(OffsetDateTime createdAt) {
        this.createdAt = createdAt;
        return this;
    }

    /**
     * Last update timestamp
     *
     * @return the updatedAt property value
     */
    public OffsetDateTime getUpdatedAt() {
        return updatedAt;
    }

    /**
     * Set the updatedAt property value
     *
     * @param updatedAt property value to set
     */
    public void setUpdatedAt(OffsetDateTime updatedAt) {
        this.updatedAt = updatedAt;
    }

    /**
     * Set updatedAt in a chainable fashion.
     *
     * @return The same instance of Pet for chaining.
     */
    public Pet updatedAt(OffsetDateTime updatedAt) {
        this.updatedAt = updatedAt;
        return this;
    }

    /**
     * Pet breed
     *
     * @return the breed property value
     */
    public String getBreed() {
        return breed;
    }

    /**
     * Set the breed property value
     *
     * @param breed property value to set
     */
    public void setBreed(String breed) {
        this.breed = breed;
    }

    /**
     * Set breed in a chainable fashion.
     *
     * @return The same instance of Pet for chaining.
     */
    public Pet breed(String breed) {
        this.breed = breed;
        return this;
    }

    /**
     * Pet color
     *
     * @return the color property value
     */
    public String getColor() {
        return color;
    }

    /**
     * Set the color property value
     *
     * @param color property value to set
     */
    public void setColor(String color) {
        this.color = color;
    }

    /**
     * Set color in a chainable fashion.
     *
     * @return The same instance of Pet for chaining.
     */
    public Pet color(String color) {
        this.color = color;
        return this;
    }

    /**
     * Pet description
     *
     * @return the description property value
     */
    public String getDescription() {
        return description;
    }

    /**
     * Set the description property value
     *
     * @param description property value to set
     */
    public void setDescription(String description) {
        this.description = description;
    }

    /**
     * Set description in a chainable fashion.
     *
     * @return The same instance of Pet for chaining.
     */
    public Pet description(String description) {
        this.description = description;
        return this;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        var pet = (Pet) o;
        return Objects.equals(id, pet.id)
            && Objects.equals(name, pet.name)
            && Objects.equals(species, pet.species)
            && Objects.equals(age, pet.age)
            && Objects.equals(isAvailable, pet.isAvailable)
            && Objects.equals(createdAt, pet.createdAt)
            && Objects.equals(updatedAt, pet.updatedAt)
            && Objects.equals(breed, pet.breed)
            && Objects.equals(color, pet.color)
            && Objects.equals(description, pet.description);
    }

    @Override
    public int hashCode() {
        return Objects.hash(id, name, species, age, isAvailable, createdAt, updatedAt, breed, color, description);
    }

    @Override
    public String toString() {
        return "Pet("
            + "id: " + getId() + ", "
            + "name: " + getName() + ", "
            + "species: " + getSpecies() + ", "
            + "age: " + getAge() + ", "
            + "isAvailable: " + getIsAvailable() + ", "
            + "createdAt: " + getCreatedAt() + ", "
            + "updatedAt: " + getUpdatedAt() + ", "
            + "breed: " + getBreed() + ", "
            + "color: " + getColor() + ", "
            + "description: " + getDescription()
            + ")";
    }

}