-- Pet Shop Database Schema
-- Migration: Create pets table

CREATE TABLE IF NOT EXISTS pets (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    species VARCHAR(50) NOT NULL,
    breed VARCHAR(50),
    age INTEGER NOT NULL CHECK (age >= 0 AND age <= 50),
    color VARCHAR(20),
    description VARCHAR(500),
    is_available BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW()
);

-- Create indexes for better query performance
CREATE INDEX IF NOT EXISTS idx_pets_species ON pets(species);
CREATE INDEX IF NOT EXISTS idx_pets_is_available ON pets(is_available);
CREATE INDEX IF NOT EXISTS idx_pets_species_available ON pets(species, is_available);
CREATE INDEX IF NOT EXISTS idx_pets_name ON pets(name);
CREATE INDEX IF NOT EXISTS idx_pets_age ON pets(age);

-- Insert some sample data
INSERT INTO pets (name, species, breed, age, color, description, is_available) VALUES
('Buddy', 'Dog', 'Golden Retriever', 3, 'Golden', 'Friendly and energetic dog, great with children', true),
('Whiskers', 'Cat', 'Siamese', 2, 'Cream', 'Calm and affectionate cat, loves to cuddle', true),
('Max', 'Dog', 'German Shepherd', 5, 'Black and Tan', 'Intelligent and loyal, well-trained guard dog', true),
('Luna', 'Cat', 'Persian', 4, 'White', 'Beautiful long-haired cat, very gentle', true),
('Charlie', 'Dog', 'Labrador', 1, 'Chocolate', 'Playful puppy, loves to fetch and swim', true),
('Bella', 'Cat', 'Maine Coon', 6, 'Orange', 'Large and friendly cat, great personality', false),
('Rocky', 'Dog', 'Bulldog', 4, 'Brindle', 'Sturdy and calm dog, good for apartments', true),
('Mittens', 'Cat', 'Tabby', 3, 'Gray', 'Independent but loving cat, great mouser', true);